### ISSUE TITLE
Give the Home Section a relevant background image. 

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#1]
After adding the background image, make sure the text "Geektober.." and the button are still visible properly, you may have to change their styling.

**Comment by ZarghamDanial** [comment]
Hey, can I take up this issue?

**Comment by sggts04** [comment]
> Hey, can I take up this issue?

Hey, thanks for your interest. However, this repo is part of an event being held exclusively for our organisation.

Thanks.

**Comment by alkatrivedi** [comment]
I would like to work on it. May I?

**Comment by JLodha** [comment]
I want to work on this

**Comment by AlacritousCreature** [comment]
I want to work on this. May I?

**Comment by Cypherdious89** [comment]
I want to work on this @sggts04

**Comment by sggts04** [comment]
@alkatrivedi go ahead

**Comment by alkatrivedi** [comment]
On it. Thanks!

**Comment by BLACK-PEARLL** [comment]
i want to work on this issue @sggts04

**Comment by alkatrivedi** [comment]
@sggts04 I have set the image. Have a look at what I did and tell me if it's okay or not. If not, what can I improve?
![Capture](https://user-images.githubusercontent.com/58396306/95664457-9dae9980-0b65-11eb-89c4-f11d60c9ad67.JPG)

**Comment by sggts04** [comment]
@alkatrivedi the text isn't too readable. Maybe you can style the text to make it readable according to the color of the background image.

**Comment by alkatrivedi** [comment]
Yeah sure!

**Comment by alkatrivedi** [comment]
How is it Now? Or anything else I can improve!
![Capture](https://user-images.githubusercontent.com/58396306/95665429-c3d83780-0b6d-11eb-89eb-7817c6068aa8.JPG)

**Comment by sggts04** [comment]
Looks good to me, make sure to add a live link in the PR details when you send the PR.
