### ISSUE TITLE
Fix Navbar cropping stuff when menu elements are clicked.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#105]
Since the navbar is hovering above and the entire page is pushed upwards to take the space of the previously non-sticky navbar, smooth scroll navigation is ending up in cropped sections.

Example:
![image](https://user-images.githubusercontent.com/20678047/95961051-28bbb800-0e22-11eb-8a46-16a01f50d521.png)
Clicking on Projects leads me to here, it assumes there is no navbar there and shows cropped up, thus, hiding the Projects heading. Ideally the section should appear below the navbar

**Comment by Vanhsiav-afk** [comment]
can i work on this?

**Comment by sggts04** [comment]
Go ahead

**Comment by Vanhsiav-afk** [comment]
![Screenshot 2020-10-14 140055](https://user-images.githubusercontent.com/58393703/95963805-bfd63f00-0e25-11eb-9c09-3299cf09e7c6.png)
Does this look good now?

**Comment by Vanhsiav-afk** [comment]
![Screenshot 2020-10-14 141119](https://user-images.githubusercontent.com/58393703/95965083-2ad44580-0e27-11eb-89e2-a87530f85f68.png)
Does this look good?

**Comment by sggts04** [comment]
Looks better, the section should start where navbar ends. And this should be done with all the menu items.
Also please don't just use a fixed margin or something, keep in mind the responsiveness on different screens, resize your window and make sure it looks fine there too.

**Comment by Vanhsiav-afk** [comment]
I've added a media query in addition to adding increaing the padding in all the sections which seems to do the work for different window sizes

**Comment by sggts04** [comment]
Cool
