### ISSUE TITLE
Change the Geekhaven logo in navbar to a white logo when dark mode is toggled on

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#106]
![image](https://user-images.githubusercontent.com/20678047/95962449-0165ea80-0e24-11eb-96cf-ca1327ad30bb.png)
When dark mode is toggled, we can barely see the black geekhaven logo. What you should do is change the geekhaven logo to a white version, when dark mode gets toggled, and then revert back to the old logo, when light mode gets toggled again.

You can find the white logo here: https://raw.githubusercontent.com/GeekHaven/GeekHaven-2020/master/images/gh.png
Or, you can possibly use css to invert the colours of the same logo, that maybe a better option.

**Comment by Aldhanekaa** [comment]
May I work on this issue?

**Comment by geeks5551** [comment]
can i work on this issue? @sggts04

**Comment by sandy9808** [comment]
Can i ?

**Comment by sggts04** [comment]
@geeks5551 go ahead
