### ISSUE TITLE
Project link should open in a new tab when 'Go to Repo' button is clicked on a Project.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#107]

**Comment by Mehul-12** [comment]
interested, pl assign.

**Comment by sggts04** [comment]
@Mehul-12 go ahead

**Comment by sruthiragupathy** [comment]
Shall i work on it?

**Comment by BLACK-PEARLL** [comment]
I want to work on it ,pl assign.@sggts04

**Comment by prakhartech** [comment]
Completed the issue Please check and accept #119 PR.
Thanks

**Comment by sggts04** [comment]
Hi @prakhartech . Thanks for your interest however this repo is part of an event being exclusively organized for our organization.
