### ISSUE TITLE
Add the discord server link to the About Section

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#108]
To the about section, add some text about the Discord Server of Geektoberfest and then hyperlink the link to the Geektoberfest Discord Server with it. You can style the hyperlink so it doesn't look too distracting.

Here is the discord server link: https://discord.gg/VQqfNAG

**Comment by Aldhanekaa** [comment]
may i work on this issue?

**Comment by shyamTayal** [comment]
I can do it.. please assign

**Comment by sggts04** [comment]
@Aldhanekaa Hey, thanks for your interest. However, this repo is part of an event being held exclusively for our organisation.

Thanks.

**Comment by sggts04** [comment]
@shyamTayal go ahead
