### ISSUE TITLE
Create a new page /profile.html which takes username as parameter and shows the details of the participant.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#125]
Create a new page profile.html which takes the username as a parameter. For example the URL would be:
`https://geekhaven.github.io/Geektoberfest-Main/profile.html?username=2802harsh`

And then according to the username provided in the URL, first you can extract the username from URL, and fetch the details from the correct json file in the contributions folder and display a page showing the details of the mentioned participant.

You can get the json file using fetch(), the files should be hosted at `https://geekhaven.github.io/Geektoberfest-Main/contributions/` so for example 2802harsh.json will be at `https://geekhaven.github.io/Geektoberfest-Main/contributions/2802harsh.json`

**Comment by thelavenderhue** [comment]
@sggts04 can I work on this?

**Comment by sggts04** [comment]
@thelavenderhue go ahead

**Comment by tsukii21** [comment]
updates?

**Comment by thelavenderhue** [comment]
@tsukii21 I'm on it

**Comment by tsukii21** [comment]
I want something to prove that you are working on this, or this issue will be reassigned

**Comment by thelavenderhue** [comment]
@tsukii21 I'll make a pr tomorrow

**Comment by sggts04** [comment]
This issue is now open.

**Comment by kumarmanish03** [comment]
I want to work on this

**Comment by sggts04** [comment]
@kumarmanish03 go ahead

**Comment by kumarmanish03** [comment]
@sggts04 Hey, Is I have to create a separate html page or page that would be of the website and include it in website also(with styling)?
Pls elaborate

**Comment by sggts04** [comment]
Its a separate page. You just have to create a page that can be accessed using the URL I mentioned. Buttons for reaching to that URL will be done through a separate issue. You can just do basic styling for now, there will be separate issues for improving the style.
