### ISSUE TITLE
Fix Geekhaven logo getting stretched

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#126]
In the navbar, the Geekhaven logo is looking stretched.. It maybe because of the use of both width and height properties instead of one. Also fix the margin around the logo, currently it has some uneven margin, make it look better.

**Comment by geeks5551** [comment]
can i work on this @sggts04

**Comment by sggts04** [comment]
@geeks5551 you already have 2 assigned issues in this repo. You still have that scroll to top issue buddy.

**Comment by geeks5551** [comment]
@sggts04 can you reasign that issue and give me this one as I am unable to fix that issue completely although I tried my best in that

**Comment by Suritam-Nandy** [comment]
I had fixed Issue #128 and opened a PR, and now I fixed #126 and its commit is with the same PR. I forgot to create another branch in my forked repo.

**Comment by sggts04** [comment]
Hi @Suritam-Nandy thanks for your interest, however this repo is part of an event being specifically held for our organization.
