### ISSUE TITLE
Fix countdown being separated from the 'Days' 'Hours' etc Labels.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#127]
![image](https://user-images.githubusercontent.com/20678047/96084625-076bd200-0edd-11eb-9f2b-e3b10a91b2f1.png)

The actual timer is separated from the Days Hours Minutes labels while actually the labels should be right below the numbers.

Fix this, however don't add extra space between the 'Event Ends In' label and the countdown, your task is to shift the 'Day Hours..' labels upwards, not the countdown downwards.

**Comment by aj0311** [comment]
Hey! Can I work on this issue?

**Comment by sggts04** [comment]
@aj0311 go ahead

**Comment by aj0311** [comment]
![Uploading Screenshot (32).png…]()
Is this okay? Or any other changes...

**Comment by aj0311** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/58393925/96166761-0b7b0c80-0f3c-11eb-89d6-2fd90c23bf19.png)
Is this okay? Or any other changes...

**Comment by sggts04** [comment]
Maybe the labels and the time can be a little more closer. Other than that, fine.
