### ISSUE TITLE
Fix Footer showing copyright to Opencode instead of Geektoberfest

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#128]
In the footer, it shows Copyright to Opencode'20 instead of Geektoberfest'20. Fix that.

**Comment by aarpit1010** [comment]
can I do this ?

**Comment by geeks5551** [comment]
Can i work on this?

**Comment by sggts04** [comment]
@geeks5551 go ahead

**Comment by Suritam-Nandy** [comment]
Can I also work on this?
I have made the change and opened a Pull Request.

**Comment by Suritam-Nandy** [comment]
I have again made the PR following the guidelines.

**Comment by sggts04** [comment]
Again @Suritam-Nandy as I already said, thanks for your interest, however this repo is part of an event being specifically held for our organization.

**Comment by Suritam-Nandy** [comment]
Okay cool.
