### ISSUE TITLE
Make the site responsive

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#13]
Currently the site breaks at mobile and tablet widths. Add responsiveness to the site, so that it looks good, especially for mobile devices.

**Comment by BLACK-PEARLL** [comment]
please ,assign me this issue @tsukii21 
i want to work on this

**Comment by Priyansh-09** [comment]
Hey @tsukii21 I wan to work on this

**Comment by shyamTayal** [comment]
I want to work on this one , Please assign this to me

**Comment by tsukii21** [comment]
You are assigned @BLACK-PEARLL . Make sure to add a link to a live page when you are making the PR.

**Comment by tsukii21** [comment]
Everyone else, thanks for the interest, there are many more interesting projects and issues coming up exclusively for students of our college.

**Comment by sggts04** [comment]
@BLACK-PEARLL are you working on this still? any update?

**Comment by geeks5551** [comment]
@sggts04 Can I work on this?

**Comment by BLACK-PEARLL** [comment]
Sir, actually my laptop got crashed, thatwhy i unable to complete my task, i will compete it my tomorrow night

**Comment by BLACK-PEARLL** [comment]
Actually my laptop got crashed, thatwhy i unable to complete my task, i will compete it my tomorrow night. 
@sggts04

**Comment by sggts04** [comment]
Ok fine you can do it by tomorrow night but after that I am gonna have to reassign if not completed.

**Comment by BLACK-PEARLL** [comment]
Sorry for inconvenience, but still my laptop in not working, and i doesn't have any other system to complete this task.

**Comment by tsukii21** [comment]
Okay. Actually I will be closing this issue. This issue will be reopened after the projects and participants sections are done to avoid any syncing conflicts.
