### ISSUE TITLE
Fix spelling of Varun's Name in Maintainers

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#137]
On special request from @starboi02, we need to fix Varun's name in maintainer names in the Projects Section, in the projects 'Chat App' and 'GOT Character App'.

His Name is Varun Bhardwaj not Varun Bharadwaj :P

**Comment by Aditya-2001** [comment]
@sggts04 I want to do this

**Comment by sggts04** [comment]
@Aditya-2001  go ahead
