### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#14]
Currently the site looks quite dull and bland. Add a good font and try to redesign the site as you see fit without changing the html structure

**Comment by BLACK-PEARLL** [comment]
please assign, me this issue @tsukii21

**Comment by Cypherdious89** [comment]
Hey @tsukii21 can you assign me this issue ?

**Comment by tsukii21** [comment]
@Priyansh-09 You are on this issue. Add a preview when pushing, so we can see what you have done.

**Comment by Mehul-12** [comment]
interested, pl assign

**Comment by Cypherdious89** [comment]
> @Priyansh-09 You are on this issue. Add a preview when pushing, so we can see what you have done.

I'll try to submit it by tonight.

**Comment by tsukii21** [comment]
cool

> > @Priyansh-09 You are on this issue. Add a preview when pushing, so we can see what you have done.
> 
> I'll try to submit it by tonight.

**Comment by Cypherdious89** [comment]
> 
> 
> @Priyansh-09 You are on this issue. Add a preview when pushing, so we can see what you have done.

Hey, check out these screenshots, and suggest if any other things can be added.

![Screenshot](https://user-images.githubusercontent.com/55129015/95683601-fdf71700-0c09-11eb-924a-18171b17ecc4.png)

The NavBar links show color transition when hovered. That _Get Started button_ is responsive, it give a slight push effect when hovered and a press effect when clicked.
![Screenshot (1)](https://user-images.githubusercontent.com/55129015/95683652-3f87c200-0c0a-11eb-9122-30b827f912d3.png)
![Screenshot (2)](https://user-images.githubusercontent.com/55129015/95683671-57f7dc80-0c0a-11eb-85f4-00c398f1b6b3.png)
![Screenshot (3)](https://user-images.githubusercontent.com/55129015/95683679-60e8ae00-0c0a-11eb-8e76-2cf202bd3e07.png)

 Those card buttons show a transition of background-color and font-color when hovered.
Please give your feedback. If this is sufficient, I can create a PR for this.

**Comment by tsukii21** [comment]
Nice work @Priyansh-09 . This issue will be closed now.
