### ISSUE TITLE
Style participants section

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#141]
Participants are finally visible but their the styling is unfinished. Add bootstrap cards or sth to make the section look better.
(the participant divs are in main.js and are dynamically being rendered from there, so keep that in mind and don't break the code)

**Comment by BLACK-PEARLL** [comment]
i want to  work on this,please assign @tuskii21

**Comment by BLACK-PEARLL** [comment]
i want to work on this @tsukii21

**Comment by BLACK-PEARLL** [comment]
please assign

**Comment by Aditya-2001** [comment]
I want to work on it

**Comment by sggts04** [comment]
@BLACK-PEARLL go ahead

**Comment by tsukii21** [comment]
@BLACK-PEARLL While you are at it, can you add images of the participants too? (I added a comment there on how to access image url)

**Comment by BLACK-PEARLL** [comment]
yes :)

**Comment by BLACK-PEARLL** [comment]
@tsukii21 please tell me where you comment "how to access image url".

**Comment by tsukii21** [comment]
right where you need it actually. have you pulled the latest changes?

**Comment by tsukii21** [comment]
Anyway you can access it as data.imageurl (in the relavant block). (in fact you can access anything this way from your json file)

**Comment by BLACK-PEARLL** [comment]
thankyou, i got that :) @tsukii21

**Comment by BLACK-PEARLL** [comment]
@tsukii21  may i change code of html in main.js which is classes for contributors section.

**Comment by tsukii21** [comment]
Yea, go ahead

**Comment by BLACK-PEARLL** [comment]
i more issue i am facing ,i.e the image of shyam tayal and aditya aggarwal is not loading on website.
please guide me @tsukii21

**Comment by tsukii21** [comment]
maybe they have provided invalid urls. Anyway send ss or a live link so I can see your progress

**Comment by shyamTayal** [comment]
My img url is of google drive if thats a problem , ???

**Comment by shyamTayal** [comment]
Do i have to add only url from the given site?

**Comment by Aditya-2001** [comment]
@BLACK-PEARLL my img url is invalid, I will change it later

**Comment by tsukii21** [comment]
@shyamTayal @Aditya-2001 change it later, not a big issue, a default image can be shown for invalid / null urls

**Comment by BLACK-PEARLL** [comment]
![Untitled](https://user-images.githubusercontent.com/60192561/96241411-bed91500-0fbf-11eb-9060-1831245fe61b.png)

**Comment by tsukii21** [comment]
Cool, if the only issue remaining is invalid urls, you can ignore it and make a pr, this bug will be taken up on a new issue

**Comment by BLACK-PEARLL** [comment]
Ok:)
