### ISSUE TITLE
Custom cursor redesign

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#147]
The current cursor is cool, but the color can be improved. Ideally, a blending mode which inverses the colors is desired, so the cursor is always visible. Also the cursor can change when hovering over a link or an icon.

**Comment by Mehul-12** [comment]
interested, pl assign

**Comment by tsukii21** [comment]
It says you have commited in this repo before, but I can't see your json file

**Comment by Mehul-12** [comment]
Yes, i haven't added my json file yet

**Comment by tsukii21** [comment]
What contributions have you made so far? (and add your json file, its how we track the contributors)

**Comment by Mehul-12** [comment]
ok, adding my json file now

**Comment by tsukii21** [comment]
ok you are assigned

**Comment by tsukii21** [comment]
updates?

**Comment by Mehul-12** [comment]
yup, i will share the live link within few minutes.

**Comment by Mehul-12** [comment]
I don't know why but this line of code doesnt seem to work.

**Comment by Mehul-12** [comment]
So shall i commit the current changes into the latest repo?

**Comment by tsukii21** [comment]
It may be because of support issues (what browser are you using?). You know, forget the blend modes(if its not working), make the colors blue again (like it was originally) and make the cursors big when hovering over a link or sth

**Comment by tsukii21** [comment]
This issue is open now

**Comment by IC1101Virgo** [comment]
Can I work on this?
