### ISSUE TITLE
Add a contact section

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#15]
Currently there's no contact section in the page. Add a section at the end before the footer and add social media icons (these links' hrefs may be left empty, we will update it).

**Comment by sandy9808** [comment]
I can do it..

**Comment by BLACK-PEARLL** [comment]
please assign me this issue  @tsukii21

**Comment by tsukii21** [comment]
Go ahead @sandy9808 . When you are making the PR, make sure to add a screenshot of what you have done

**Comment by maityankan10** [comment]
please assign this to me

**Comment by tsukii21** [comment]
Everyone else, there are many more issues out there, and many more coming up. Don't give up and keep hacking!

**Comment by sandy9808** [comment]
Is it fine @tsukii21 
![Uploading image.png…]()

**Comment by sandy9808** [comment]
Is it fine @tsukii21 ?
![image](https://user-images.githubusercontent.com/58395595/95672637-2bb76e00-0bc0-11eb-8941-ead3cda9c379.png)

**Comment by shyamTayal** [comment]
i want to work on this one ... Can i?

**Comment by tsukii21** [comment]
@sandy9808 Well, it was mentioned clearly that we needed social media icons, not a form (we don't really need a form). Anyway thanks for the effort

**Comment by tsukii21** [comment]
@shyamTayal You are being assigned.

**Comment by tsukii21** [comment]
@sandy9808 you can try on the icons still now, if it turns out good, we will reconsider it

**Comment by shyamTayal** [comment]
Can i take icons from font awesome or do i have to manully add images? Because for font awesome icons i have an idea that i can make them glowing on hovering ..

**Comment by tsukii21** [comment]
@shyamTayal Your PR was good, I merged it, but somehow its breaking. Please pull new changes in your local repo and fix the issue. It must be trivial. Then make a new PR.I will merge it immediately

**Comment by tsukii21** [comment]
I am closing this issue with @shyamTayal 's implementation. Good work!

**Comment by shyamTayal** [comment]
Thank You!
Can you please elaborate where it is breaking? I have pulled new changes into my local repo. It seems perfectly fine to me.

-------- Original message --------
