### ISSUE TITLE
navbar redesign 2

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#162]
The night mode toggle button should not be in the middle, but in the extreme right. Also if the bottom shadow on link hover can be removed, and there's a transition duration to the hover effect, it will look better.  (the navbar has a responsive feature, so also see that your redesign works well in mobile devices). Take inspiration from this-
![image](https://user-images.githubusercontent.com/38427014/96263674-e42a4b00-0fe0-11eb-81b4-7d8c4491c03b.png)

**Comment by sandy9808** [comment]
Can I do it?

**Comment by BLACK-PEARLL** [comment]
can i work on this @tsukii21 
please assign

**Comment by tsukii21** [comment]
@sandy9808 I can't see you in the contributors section. Have you added your json file? (its necessary)

**Comment by tsukii21** [comment]
@BLACK-PEARLL I can't find your json file too. add it

**Comment by Mehul-12** [comment]
interested , may I?

**Comment by tsukii21** [comment]
@Mehul-12 finish your assigned issue first

**Comment by sandy9808** [comment]
> @sandy9808 I can't see you in the contributors section. Have you added your json file? (its necessary)

OK, i will add it.

**Comment by BLACK-PEARLL** [comment]
@tsukii21 ,okk i will add it as soon as possible.

**Comment by BLACK-PEARLL** [comment]
please assign me this issue @tsukii21

**Comment by s-282** [comment]
can i work on this @tsukii21 ?

**Comment by tsukii21** [comment]
@s-282 Have you contributed before? Have you added your json file?

**Comment by s-282** [comment]
No , i haven't contributed

**Comment by tsukii21** [comment]
Ok you are assigned. Dont break the existing structure and functionality and respond with a live link when you are done

**Comment by tsukii21** [comment]
Any updates?

**Comment by s-282** [comment]
is this ok?
https://s-282.github.io/

**Comment by tsukii21** [comment]
Cool. can you make the animated underlines a bit thinner to match the font weight? And also push the links to the left next to the brand?

**Comment by s-282** [comment]
ok

**Comment by s-282** [comment]
ok, i'll do it.

**Comment by s-282** [comment]
Have a look ,
 https://s-282.github.io/

**Comment by tsukii21** [comment]
Don't change the size of the links or the brand, they look good as they were originally. The underlines could be thinner but other than that everything is perfect. Make a PR after making these changes

**Comment by s-282** [comment]
ok, I'll make the changes.
