### ISSUE TITLE
Participants default picture

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#163]
some participants have provided invalid image urls. See to it that a default picture is shown instead of whats currently showing.

**Comment by shahidsiddiqui786** [comment]
i want to work on it

**Comment by tsukii21** [comment]
Ok, take care not to interfere with the current structure. The participants are being rendered dynamically from main.js, so study how it is working solve this issue

**Comment by shahidsiddiqui786** [comment]
ok :)

**Comment by shahidsiddiqui786** [comment]
what should be the default picture?
