### ISSUE TITLE
participant section redesign

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#166]
the current design is good, but the participant divs could be smaller and the aspect ratio of the original image should remain intact

**Comment by BLACK-PEARLL** [comment]
can i work on this?
@tsukii21

**Comment by tsukii21** [comment]
@BLACK-PEARLL go ahead (and add your json file)

**Comment by tsukii21** [comment]
Updates?

**Comment by BLACK-PEARLL** [comment]
@tsukii21 
sorry,i will done it by tomorrow afternoon
due to problem which occur in my laptop.

**Comment by tsukii21** [comment]
If no progress is reported by tomorrow, this issue will be reassigned. So keep that in mind

**Comment by BLACK-PEARLL** [comment]
i try my best to do it by tomorrow :)

**Comment by BLACK-PEARLL** [comment]
![Untitled](https://user-images.githubusercontent.com/60192561/96359875-37151700-1135-11eb-810e-69c14a74c8eb.png)

**Comment by BLACK-PEARLL** [comment]
is this fine?
 @tsukii21

**Comment by tsukii21** [comment]
Looks fine, make a PR with the live link included.

**Comment by BLACK-PEARLL** [comment]
ok
