### ISSUE TITLE
make this site responsive

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#172]
All the major work is done, but the site is still unbearable in smartphones. Making this extended site responsive without breaking the existing functionality can prove to be a challenge, but we need help and any contribution is welcome.

**Comment by shahidsiddiqui786** [comment]
I want to work on this.

**Comment by tsukii21** [comment]
this is a big issue, you think you can handle it?

**Comment by KGene1901** [comment]
I can take a look at it as well to see what I can do

**Comment by shahidsiddiqui786** [comment]
I will try the best to do. 

> this is a big issue, you think you can handle it?

I will try to do that .

**Comment by tsukii21** [comment]
@KGene1901 we appreciate your interest, but this repo is exclusively for the students of our college

**Comment by tsukii21** [comment]
@shahidsiddiqui786 you are assigned. Do a good job, Keep syncing the repo with the original and make sure to provide a live link when you are done
