### ISSUE TITLE
Smooth scrolling on clicking a navbar menu item only works on Chrome

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#175]
If I click on lets say 'Projects' menu item in the nav bar, the website should smoothly scroll to the projects section, instead of just snapping into it. (Just like there is scroll animation in the Scroll To Top button)

**Currently, smooth scrolling is implemented but only works on Chrome/Brave browsers, make it work on all browsers. (Edge etc)**

**Comment by sandy9808** [comment]
I can do this,  please assign me.

**Comment by sggts04** [comment]
@sandy9808 go ahead.

**Comment by sandy9808** [comment]
I am not able to figure out in which browser it is not working. Can you tell me the browser in which it is not working?

**Comment by sggts04** [comment]
Okay it seems to be fixed now for some reason :| Earlier it wasn't working on Edge. I'll close the issue, sorry.
