### ISSUE TITLE
Make the navbar sticky

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#19]
The navbar should be visible from anywhere on the page. make it sticky without breaking the existing site. A live preview is expected with a PR

**Comment by cosmoimai** [comment]
@tsukii21, I would like to work on this . can you assign it to me

**Comment by tsukii21** [comment]
Go ahead @cosmoimai

**Comment by shyamTayal** [comment]
can i work on this one ?

**Comment by cosmoimai** [comment]
@tsukii21 can you explain what live preview means?

**Comment by tsukii21** [comment]
After forking and pushing changes to your forked repo, you can publish the page on github pages. You can search how to do it, its pretty simple

**Comment by cosmoimai** [comment]
Ok

**Comment by cosmoimai** [comment]
so, I have to publish a page and give the link of the page. is it?

**Comment by tsukii21** [comment]
yea exactly

**Comment by cosmoimai** [comment]
So, I don't have to make a new branch for that?

**Comment by cosmoimai** [comment]
done #26

**Comment by tsukii21** [comment]
Good work. I am closing this issue
