### ISSUE TITLE
Shorten too big Abouts of Participants with "..."

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#191]
Some participants have too big Abouts. Example:
![image](https://user-images.githubusercontent.com/20678047/96371511-a7488a80-117f-11eb-850d-dc2cd09e98a2.png)

and it is messing with the styling of the card.

So if the About of someone is bigger than some word limit, then end it with "..." after the limit. For example, you can set the character limit as 70. If someone has About more than 70 then you can just end it after 70 with "...".
70 is just a random guess, find the number which is big enough and doesn't mess with the styling.

**Comment by BLACK-PEARLL** [comment]
i want to work on this @sggts04

**Comment by sggts04** [comment]
@BLACK-PEARLL go ahead.
Also please center the fb/github buttons. The text is centered but the social buttons aren't.

**Comment by BLACK-PEARLL** [comment]
okk @sggts04

**Comment by BLACK-PEARLL** [comment]
@sggts04 , i after adding "..." after the limit ,for long about 
i also have to add read more so anyone if want to read complete about
he/she can click that button and able to read complete about anyone of particioants?

**Comment by sggts04** [comment]
No no, no need for that.

**Comment by BLACK-PEARLL** [comment]
![Untitled](https://user-images.githubusercontent.com/60192561/96420408-1b803e00-1213-11eb-9169-fa1ec1d9a1ea.png)
is this fine?

**Comment by sggts04** [comment]
Yes

**Comment by BLACK-PEARLL** [comment]
okk
