### ISSUE TITLE
The Project Cards are not the same size when hovered on.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#196]
For example, when hovering on some of the project cards, this is what happens:

![image](https://user-images.githubusercontent.com/20678047/96403742-c0405280-11f6-11eb-81b1-858dc4bf87bf.png)

![image](https://user-images.githubusercontent.com/20678047/96403781-cfbf9b80-11f6-11eb-974e-e04c5fb4d5d9.png)

As you can see, when hovered, according to the text there, some cards become shorter in height, while some cards become larger in height. This shouldn't be the case, the cards shouldn't change their height when hovered, make sure the cards remain the same height as before when hovered.

**Comment by Mehul-12** [comment]
interested, pl assign

**Comment by sggts04** [comment]
@Mehul-12 go ahead.

**Comment by Anurag-ak99** [comment]
is the issue open? then pls assign it to me.
