### ISSUE TITLE
Add a new page /leaderboard.html which fetches all the participants and displays their number of PRs in a sorted manner.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#197]
You can look at how the participants are being fetched in the Participants section of the main site. (Refer the last bit of code in [main.js](https://github.com/GeekHaven/Geektoberfest-Main/blob/main/public/js/main.js) )

In the same way, you have to fetch these participants in new page leaderboard.html, and then create a table where the participants appear in a sorted way according to their number of pull requests.

**Comment by thelavenderhue** [comment]
@sggts04 can I work on this?

**Comment by shahidsiddiqui786** [comment]
I want to work on this..

**Comment by sggts04** [comment]
@thelavenderhue go ahead.
