### ISSUE TITLE
Mobile Navbar doesn't have a background colour when clicking on hamburger.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#198]
Screenshot:
![image](https://user-images.githubusercontent.com/20678047/96404280-27123b80-11f8-11eb-8f6c-fe820d38cabd.png)

As you can see, when the hamburger is clicked, there is no background behind the menu items, that shouldn't be the case, it looks out of place. It should look as if it was extended from the navbar, so make the background of the drop down navbar, the same color as the navbar.

**Comment by geeks5551** [comment]
can i work on this @sggts04

**Comment by sggts04** [comment]
@geeks5551 go ahead.

**Comment by srishtij2000** [comment]
Can I work on this issue
