### ISSUE TITLE
Improve the colouring of the site, and also update the About Section text.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#2]
Currently the site looks very dull, improve the colouring choice. You can search for good colour palletes.
Also, update the text in About section with information about Geektoberfest.

**Comment by tjrelyts** [comment]
I'll take up this issue.

**Comment by sggts04** [comment]
> I'll take up this issue.

Hey, thanks for your interest. However, this repo is part of an event being held exclusively for our organisation.

Sorry for the inconvenience.

**Comment by maityankan10** [comment]
can I contribute for hacktoberfest

**Comment by Jyotika999** [comment]
I want to work on this.

**Comment by sggts04** [comment]
@Jyotika999 The event begins at midnight! We can only start assigning issues then.

**Comment by JLodha** [comment]
I want to work on this
Since the official mail is released now then shouldn't I get the priority?

**Comment by sggts04** [comment]
@JLodha sure go ahead.

**Comment by Cypherdious89** [comment]
I want to work on this @sggts04

**Comment by BLACK-PEARLL** [comment]
i want to work on this issue @sggts04

**Comment by Saggittarius-A** [comment]
i want to work on this.

**Comment by geeks5551** [comment]
i want to work on this @sggts04

**Comment by shyamTayal** [comment]
Can i work on this
