### ISSUE TITLE
Add a mentors section

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#205]
Similar to the participants section, add a mentors section below. 

You can check the projects section for getting the names of mentors.

Each mentor should be in a card, with details such as Photo, Name, Github Link, Facebook Link. The card styling can be similar to the participants section.

Also add the Mentors menu item to the nav bar.

**Comment by Ranveer251** [comment]
I want to work on this.

**Comment by sggts04** [comment]
@Ranveer251 go ahead.

**Comment by srishtij2000** [comment]
Can I work on this issue?
