### ISSUE TITLE
Link Participant cards to their corresponding Profile.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#211]
Along with the Github/Fb Buttons, add a profile button to the participant cards which links the participant's profile.

A participant's profile will be located at:
```
https://geekhaven.github.io/Geektoberfest-Main/profile.html?username=xyz123
```
**where `xyz123` is the username of the participant.**

The username of the participant should be stored in the variable `participant` in the js code where the participant cards get generated.

**Comment by Mehul-12** [comment]
interested, pl assign

**Comment by sggts04** [comment]
@Mehul-12 go ahead

**Comment by ankitgauri26** [comment]
Can i work on this if it is not resolved yet?

**Comment by kumarmanish03** [comment]
@sggts04 Can I work on it?

**Comment by sggts04** [comment]
@Mehul-12 any update? or I will have to reassign this.

**Comment by Mehul-12** [comment]
yup, will try till tonight.
if I am unable to do then pl reassign.

**Comment by kumarmanish03** [comment]
@sggts04 could you assign it to me?

**Comment by sggts04** [comment]
@kumarmanish03 go ahead. But this will be last issue assigned to you in Geekhaven Repos. There is a 6 PR limit to Geekhaven repos, you have already added 4 PRs, 1 PR is merged but you haven't added it to your file yet, and last this one. If you want to add more contributions to Geektoberfest, then you can contribute to other public repos on Github, and add them to your file.
