### ISSUE TITLE
Redesign profile page.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#212]
Each person's profile page is now available.

Example URL: `https://geekhaven.github.io/Geektoberfest-Main/profile.html?username=2802harsh`. You can change `2802harsh` to your own username to get your own profile.

You have to redesign this profile page to look better(Make sure to check pages of different profiles to verify your styling is consistent):

1. Improve the header. Better font, also fix the grammer, coloring.
2. Show the number of PRs made.
3. Show the PRs in a styled table instead of a list, and make sure they are hyperlinked(they cannot be clicked as of now)
4. Improve the overall font and sizes etc, make it look good.
5. Make the social icons a little bigger and better placed.

**Comment by 2802harsh** [comment]
Pls assign this issue to me

**Comment by sggts04** [comment]
go ahead

**Comment by Illusion47586** [comment]
Hey! I would like to contribute!

**Comment by Johnisaig** [comment]
I want to work on this.

**Comment by 2802harsh** [comment]
@sggts04 please review the PR

**Comment by 2802harsh** [comment]
@sggts04 I have added a new PR. Please review
