### ISSUE TITLE
Remember Dark/Light mode preference

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#226]
Make the website locally remember the Dark Mode/Light Mode preference of the user. If I toggled Dark Mode on, then next time I open the site, it should default to Dark Mode toggled on. Similar with  Light Mode.

You'll have to save user's preference in localStorage of the user's browser.

**Comment by BLACK-PEARLL** [comment]
can i?

**Comment by ankitgauri26** [comment]
Can i Work on this?
