### ISSUE TITLE
Add smooth scroll on nav-link click

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#23]
Currently, clicking the links on navbar scrolls the page abruptly, the scroll should be smooth. This may need a bit of JS. Add your JS in main.js in public/js and add a link to this file too in the html file

**Comment by CadencePrestissimo** [comment]
I would like to work on it .

**Comment by sggts04** [comment]
@CadencePrestissimo go ahead!

**Comment by shahidsiddiqui786** [comment]
I want to work on it.

**Comment by tsukii21** [comment]
@CadencePrestissimo send a live link of your working repo. smooth nav is working but everything else is gone

**Comment by tsukii21** [comment]
Please respond quickly or we will roll back your PR merge

**Comment by CadencePrestissimo** [comment]
https://nervous-mirzakhani-70f62c.netlify.app

**Comment by CadencePrestissimo** [comment]
Sorry, I saw it late.

**Comment by tsukii21** [comment]
Link the repo your netlify app is based on. I saw your forked repo. Its live preview(on github pages) is different from your netlify preview.
Your smooth nav code is working and once I confirm that it is synced with the latest changes in our main repo, I will merge it.

**Comment by CadencePrestissimo** [comment]
https://cadenceprestissimo.github.io/Geektoberfest-Main/
This is the one from the github-pages,  Its also same

**Comment by tsukii21** [comment]
yeah its all right (I was actually opening the original geekhaven live preview from your repo, my bad). Ok, make a new PR. This time it should be all right.

**Comment by tsukii21** [comment]
Okay I will be closing this issue. Good work @CadencePrestissimo
