### ISSUE TITLE
Add a Leaderboard menu item to the navbar

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#230]
Leaderboard is now available at `https://geekhaven.github.io/Geektoberfest-Main/leaderboard.html`

Add it to the navbar.

**Comment by ankitgauri26** [comment]
@sggts04 - can i work on this?

**Comment by sggts04** [comment]
Hi @ankitgauri26 , thanks for your interest, however this repo is part of an event being held exclusively for our organization.

**Comment by BLACK-PEARLL** [comment]
Can i?

**Comment by thelavenderhue** [comment]
@sggts04 can I work on this?
