### ISSUE TITLE
Instead of Github URL, link each participants profile URL in the leaderboard

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#231]
Currently in the leaderboard, there is a github column and it links to the Github Profile of the participant.

Instead of that, change it to a 'Profile' column, and link each person's geektoberfest profile there. The profile of each participant is available at:
`https://geekhaven.github.io/Geektoberfest-Main/profile.html?username=xyz123` where `xyz123` is the username. 
You'll have to understand the JS by which the table is being generated, and there instead of github URL, put geektoberfest profile url.

**Comment by Cypherdious89** [comment]
Can I do this ??

**Comment by sggts04** [comment]
@Priyansh-09 your 6th issue just got assigned to you. If you want to contribute more you can contribute to other public repositories and add them to your file. If you have made any other public contributions after 10 Oct, you can add them to your file too.

**Comment by Cypherdious89** [comment]
Okay, will add them too.

**Comment by Codedude1** [comment]
Can I work on this?

**Comment by sggts04** [comment]
@Codedude1 go ahead.
