### ISSUE TITLE
Improve Styling of Leaderboard

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#232]
Currently the leaderboard doesn't look that good.

1. Choose a better background colour, something more minimal and light, it doesn't necessarily need to be a gradient either, right now it is just too flashy and doesn't good look at all.
2. Add a good looking header with the heading 'Geektoberfest'20 Leaderboard'
3. Improve the table styling if possible, right now it looks a bit plain, you can google different table styles to get some inspiration.

**Comment by Cypherdious89** [comment]
Can I do this ?

**Comment by sggts04** [comment]
@Priyansh-09 go ahead.
