### ISSUE TITLE
Make the Scroll-To-Top button appear in front

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#233]
Currently, in mobile view, the Scroll-To-Top button goes behind the participant cards or the project cards and then it can't be clicked. Make the Scroll-To-Top appear at top, at highest priority of other elements.

**Comment by tanishbaansal** [comment]
is this issue still opened ?

**Comment by sggts04** [comment]
Hi @tanishbaansal, thanks for your interest however this repo is part of an event exclusive to our organization.

**Comment by BLACK-PEARLL** [comment]
Can i?

**Comment by sggts04** [comment]
@BLACK-PEARLL go ahead.
