### ISSUE TITLE
Replace images that couldn't be loaded with a default image.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#248]
In the leaderboard, some of the participants' images are not loading and giving errors.

They are showing up as this and its not looking good;
![image](https://user-images.githubusercontent.com/20678047/96738733-a6606480-13dc-11eb-85e7-f426e6b939f0.png)

If an image gives an error when loading, then replace it with a default image.

You can comment and show the default image you are using here before making a PR, so that there aren't any extra revisions in that case.

**Comment by kumaraditya2002** [comment]
can i work on this

**Comment by sggts04** [comment]
go ahead @kumaraditya2002
