### ISSUE TITLE
Remove 'Issue Link' Column from the PRs table in Profile Page

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#251]
As cool as it sounds, the issue link column actually doesn't do anything and just links the API response for the same the issue number as the PR number, which doesn't make any sense. So remove that column entirely.

**Comment by kumaraditya2002** [comment]
can i

**Comment by sggts04** [comment]
@kumaraditya2002 go ahead. Also make sure to add your PR file and update it with your merged PRs.
