### ISSUE TITLE
Profile Page navbar links don't work

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#252]
Right now, due to the extra `../` in the navbar links of the Profile Page, they are navigating to a different website than the actual Geektoberfest website, fix that. The index.html and leaderboard.html files are in the same folder as profile.html, not a folder above.

**Comment by BLACK-PEARLL** [comment]
can i?

**Comment by sggts04** [comment]
@BLACK-PEARLL there is a 6 PR limit to Geekhaven repos. Right now you have already documented 4 of your PRs, 5th one is merged but you haven't added it yet, and there is already a 6th issue assigned to you.

Also, please note that in your PR file you have mentioned issue links instead of PR links due to which your profile page is appearing as broken. Next time you update your file, go through all your links and replace all the issue links with PR links.

Also, if you want to contribute more after Geekhaven repos, you can contribute to other public Repos on Github and add them to your file!

**Comment by kumarmanish03** [comment]
I want to work on it

**Comment by sggts04** [comment]
@kumarmanish03 go ahead.
