### ISSUE TITLE
Add a preloader gif to the Leaderboard table when it is fetching participants

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#264]
When the leaderboard page is fetching and loading the participants, add a preloader to the leaderboard table which fades out when the table gets loaded.

Don't add a preloader to the whole leaderboard.html page, but only to the table when it is fetching participants.

**Comment by kumaraditya2002** [comment]
can i work on this??

**Comment by sggts04** [comment]
@kumaraditya2002 go ahead.
