### ISSUE TITLE
Add a preloader gif to the PR table in the profile page when the PRs are getting fetched.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#265]
In the profile page, the table with the details of PRs takes some time to load, add a preloader gif for that table. Make sure the gif you choose matches the vibe of the page.

Don't add a preloader to the whole profile.html page, but only for the PR table while its loading.

**Comment by shahidsiddiqui786** [comment]
Can i

**Comment by sggts04** [comment]
@shahidsiddiqui786 go ahead.
