### ISSUE TITLE
Fix Social Links in footer of profile page

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#272]
The Social Links in the footer of profile page are styled wrong.

Here's how it looks in Light Mode
![image](https://user-images.githubusercontent.com/20678047/96902311-ffe69300-14b1-11eb-9866-a9ec52526bbd.png)

and in Dark Mode
![image](https://user-images.githubusercontent.com/20678047/96902516-3f14e400-14b2-11eb-9d9e-71540f687c43.png)

Fix these colours, they look out of place.

**Comment by kumaraditya2002** [comment]
can i?

**Comment by charlygg** [comment]
Is still open this issue?

**Comment by sggts04** [comment]
@kumaraditya2002 go ahead.
