### ISSUE TITLE
When clicking on someone's profile from the leaderboard, it should open in a new tab.

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#283]
When clicking on someone's profile page(details column) from the leaderboard page, the profile should open on a new tab instead of the same tab.

**Comment by Aditya-2001** [comment]
i want to do it

**Comment by za-h-ra** [comment]
I just did it

**Comment by sggts04** [comment]
@Aditya-2001 go ahead.

**Comment by za-h-ra** [comment]
@sggts04 you closed my PR, just wondering, did I not get it?

**Comment by sggts04** [comment]
@zahrakhadijha Thanks for your interest however this repo is part of an event being held exclusively for our organization.

**Comment by za-h-ra** [comment]
> @zahrakhadijha Thanks for your interest however this repo is part of an event being held exclusively for our organization.

Gotcha! Thanks
