### ISSUE TITLE
Add Saarani-Frontend to the Projects list

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#285]
You can find its repo in the Geekhaven organization. Add it as a project in the projects section of the main site.

**Comment by Aditya-2001** [comment]
I want to do this

**Comment by sggts04** [comment]
@Aditya-2001 you can only work at max 2 issues at a single time in a repo

**Comment by kamal-kaur04** [comment]
Hi @sggts04, Can I take up this issue?

**Comment by Aditya-2001** [comment]
@sggts04 I have created pr for one issue, so I have one task, can I take up this issue now?

**Comment by sggts04** [comment]
@Aditya-2001 go ahead. Also don't forget to update your PR file.

**Comment by Aditya-2001** [comment]
Sir pr of #283 issue is not created till now by me

**Comment by Aditya-2001** [comment]
Can I create pr of #283 with this issue?

**Comment by sggts04** [comment]
Didn't you solve both the issues with that PR? If you commit changes after creating a PR and the PR is not yet merged, that new commit gets added to the previous PR aswell

**Comment by Aditya-2001** [comment]
oh @sggts04 , same thing has happened, commit for #283 has been already merged
