### ISSUE TITLE
Search bar in profile page should search when enter is pressed also

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#297]
Right now, after typing the username in search bar of profile page, you have to click the search button to go to the profile, make it so that just pressing enter should also act as submitting the search.

**Comment by RedLinus** [comment]
I take fix this one 🙂

**Comment by sggts04** [comment]
@RedLinus thanks for your interest however this repo is part of an event being held exclusively for our organization.

**Comment by RedLinus** [comment]
@sggts04 Okey, I understand. Good luck with your event! 😄

**Comment by kumaraditya2002** [comment]
can i

**Comment by Parasagrawal** [comment]
can i work on this

**Comment by sggts04** [comment]
@kumaraditya2002 any progress?
