### ISSUE TITLE
Add all the projects

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#37]
In the projects section, add all the projects involved in Geektoberfest as cards. Add Relevant image for each repo, Project Title, Description, Maintainer Names and then a repo link button.

**All the projects marked with 'hacktoberfest' tag in the GeekHaven org are part of Geektoberfest.**

**You can make use of Bootstrap cards, just make sure the Cards look good, the current card template present there is not to be used, it doesn't look that good.**

**Comment by Capt-Titanium** [comment]
heyy!,  can I work on this issue?

**Comment by sggts04** [comment]
@Capt-Titanium go ahead

**Comment by sggts04** [comment]
@Capt-Titanium are you still working on this?

**Comment by Capt-Titanium** [comment]
Yes @sggts04 , I will be sending the PR shortly.
