### ISSUE TITLE
Convert the navbar into a hamburger menu for mobile view

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#4]
You can use Bootstrap/Jquery.

**Comment by AlacritousCreature** [comment]
I want to work on this. May I?

**Comment by geeks5551** [comment]
Hey can you pls assign me this issue? looks interesting

**Comment by sggts04** [comment]
@AlacritousCreature go ahead.

**Comment by Cypherdious89** [comment]
I want to work on this @sggts04

**Comment by BLACK-PEARLL** [comment]
i want to work on this issue @sggts04

**Comment by shyamTayal** [comment]
Can i work on this one ? Please assign
