### ISSUE TITLE
Link all the Social Icons in the footer to the Social Media Accounts of GeekHaven

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#51]

**Comment by shyamTayal** [comment]
i can do that

**Comment by sggts04** [comment]
@shyamTayal go ahead.

**Comment by shyamTayal** [comment]
where do i get the logo for the geekhaven website to add it ?

**Comment by sggts04** [comment]
You don't need that. Just link the existing icons in the contact section to corresponding Geekhaven accounts.
