### ISSUE TITLE
Add all the Participants

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#52]
By dynamically using the JSON files in the contributions/ folder, add the details of all participants in the form of Cards.

A participant card should have their image, name, about, buttons to their fb/github, and number of PRs they have made so far.

DON'T USE THE CARD TEMPLATE ALREADY PRESENT, it doesn't look that good. You can use Bootstrap Cards.

Make sure to separate the JS into a js file in the public folder instead of adding JS to your html file.

**Comment by Aditya-2001** [comment]
I want to work on it

**Comment by sggts04** [comment]
@Aditya-2001 sure

**Comment by tsukii21** [comment]
Any updates @Aditya-2001 ?

**Comment by Aditya-2001** [comment]
I have tried 4-5 different approach to read the json file, but every time the js file is showing error like: Cannot use import statement outside a module, Uncaught ReferenceError: require is not defined at, xmlhttprequest blocked.
I am trying to resolve the error. I need some time.

**Comment by sggts04** [comment]
@Aditya-2001 any progress? Unless you feel you can complete by today, I'm gonna have to reassign this soon

**Comment by BLACK-PEARLL** [comment]
I want to work on it @sggts04

**Comment by sggts04** [comment]
Is your laptop working now? The issue shouldn't sit for another 2 days without any progress..

**Comment by Aditya-2001** [comment]
@sggts04 I am still getting the same error. You can reassign it

**Comment by BLACK-PEARLL** [comment]
yes,now working perfectly :) @sggts04

**Comment by sggts04** [comment]
@BLACK-PEARLL go ahead

**Comment by BLACK-PEARLL** [comment]
@sggts04  , i have a query that,as in contributions section there are different json file for each contributors(i.e 33 json files) ,so i have to fetch data fom each file one by one. please guide me in this.

**Comment by sggts04** [comment]
@BLACK-PEARLL thats the problem everyone is facing. If you can figure out some method (maybe with Github API) to get the names of all the files in the repo, I guess then you can iteratively fetch all those files.

**Comment by BLACK-PEARLL** [comment]
@sggts04  thankyou:)

**Comment by BLACK-PEARLL** [comment]
@sggts04 ,i tried ,but unable to solve this issue :(
unassign me for this issue.

**Comment by tsukii21** [comment]
Okay I am taking up this issue.
