### ISSUE TITLE
Add a preloader to the website

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#55]
Add a cool looking preloader to the website. You can use a gif, but make sure its transparent.

**Comment by shyamTayal** [comment]
i want to work on it . Please assign

**Comment by sggts04** [comment]
@shyamTayal go ahead

**Comment by shyamTayal** [comment]
i am having a problem here. I have added a gif but it is not showing up on the page and also if does it stay there even after loading
see following code snippet:

`
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <div id="preloader"></div>
`

`
$(function() { 
    $(window).on("load", function() {
        $('#preloader').remove();
    });
});
`

`#preloader{
  position: fixed;
  left: 0;
  top: 0;
  z-index: 99999; 
  width: 100%;
  height: 100%;
  overflow: visible;
  background: rgba(240,240,240,0.2) url('./rocket.gif') no-repeat center center;
}
`

**Comment by tsukii21** [comment]
Can you give a link to your repo (which I believe is already hosted on github)?

**Comment by tsukii21** [comment]
make sure the jquery link is after everything in body tag (if you have pulled the latest changes there should already be a jquery link in the proper position) and the link to main.js is after the jquery link. Also, since the site is static and there is almost nothing there, the browser loads the page instantly and you can't see your preloader. Use a setTimeOut or something to make sure the loader stays for like a second or sth to test

**Comment by shyamTayal** [comment]
I did what you said exactly still it is same as before

**Comment by shyamTayal** [comment]
I am actually facing problem in syncing the repo .So i copied the code from original repo .And now it showing fatal error.

**Comment by shyamTayal** [comment]
Now i am able to remove the preloader on loading but it doesn't play the gif

**Comment by shyamTayal** [comment]
[https://shyamtayal.github.io/Geektoberfest-Main/](url) : Live preview

**Comment by sggts04** [comment]
no preloader is showing on that link

**Comment by shyamTayal** [comment]
Now i am able to remove the preloader on loading but it doesn't play the gif.....

**Comment by sggts04** [comment]
You have used the wrong path for rocket.gif, its somewhere else but path is trying to find it somewhere

**Comment by shyamTayal** [comment]
Got it , I didn't consider that css file is in public/css directory

**Comment by tsukii21** [comment]
Any updates?

**Comment by shyamTayal** [comment]
Gif is showing but now it doesn't disappear after loading. Trying to fix that and also a major problem occured while i was pulling new changes into my forked repository. 
Apparently i might have made a mistake so now all the contribution json files have changed

**Comment by sggts04** [comment]
@shyamTayal any progress? If you can complete it in a few hours then fine else I'm gonna have to reassign this

**Comment by shyamTayal** [comment]
I have tried a lot of things but the preloader won't leave the screen so you can unassign me.   @Priyansh-09 was saying he is interested and has a great idea about the preloader so you can assign him.

**Comment by Cypherdious89** [comment]
> 
> 
> I have tried a lot of things but the preloader won't leave the screen so you can unassign me. @Priyansh-09 was saying he is interested and has a great idea about the preloader so you can assign him.

@sggts04 I think you should assign it to someone else, not me. Everyone should get a chance to contribute.

**Comment by sggts04** [comment]
Yes, this issue is now open for others to claim.

**Comment by kumarmanish03** [comment]
I want to work on it

**Comment by sggts04** [comment]
go ahead

**Comment by sggts04** [comment]
@kumarmanish03 also fix your last pr, the website you linked is absolutely broken

**Comment by kumarmanish03** [comment]
@sggts04 I see, ;) , I have made a new pr for that , review it https://github.com/GeekHaven/Geektoberfest-Main/pull/103
