### ISSUE TITLE
Fix Social Icons in contact section not visible

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#57]
Most Social Icons in the contact section are not visible, there is some class issue there. Make them visible again!

Make sure to update your repo to the latest version of this repo first, so you can see the issue and also to avoid conflicts.

**Comment by Cypherdious89** [comment]
Can I do this @sggts04 ??

**Comment by sggts04** [comment]
@Priyansh-09 go ahead
