### ISSUE TITLE
Add a favicon and also add GeekHaven logo to the navbar

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#7]
Add the GeekHaven logo as a favicon and also add it beside the Geektoberfest'20 heading in the navbar.

If you use a local image instead of a URL, make sure to put it in a seperate /public/images folder.

**Comment by aj0311** [comment]
@sggts04 Can I work on this issue?

**Comment by sggts04** [comment]
@aj0311 go ahead

**Comment by caseymhunt** [comment]
Favicon added (compatible with all devices) and logo added to the header to match height of the text. This size is easy to adjust if you'd like the image larger.

**Comment by sggts04** [comment]
Hi, @caseymhunt this issue has already been assigned to somebody else. I'm closing the mentioned PR.

**Comment by caseymhunt** [comment]
Lol- ok. The work is done but sure.

**Comment by Codedude1** [comment]
I wanna wok on this

**Comment by Codedude1** [comment]
@sggts04 Is this fine ?

![Screenshot 2020-10-13 101418](https://user-images.githubusercontent.com/53789050/95816902-dbfeb100-0d3d-11eb-9e8f-ffd840195bae.png)

**Comment by sggts04** [comment]
if the favicon could be transparent then it would be better, other than that, looks good.
