### ISSUE TITLE
Add a 'Scroll to Top' Button

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#76]
It should be floating in the bottom right side when scrolling down. Choose an appropriate icon for the button

**Comment by geeks5551** [comment]
can i work on this issue @sggts04 ?

**Comment by sggts04** [comment]
@geeks5551 go ahead

**Comment by Cypherdious89** [comment]
Is this issue still open @sggts04 ?? I wanna work on this.

**Comment by sggts04** [comment]
I had given @geeks5551 some more time, if he doesn't deliver by today then I will reassign

**Comment by sggts04** [comment]
@Priyansh-09  go ahead. Make sure the button should only visible when I am scrolled down, not when I am already at the top. Also you'll have to use jquery or something so that when I click the button, it actually visibly scrolls to the top, instead of just snapping to the top.
