### ISSUE TITLE
Add a Night Mode Toggle Button

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#79]
Add a button which lets you toggle between Night Mode and the current color scheme.

For implementing dark mode colors, you can google some good dark mode color palettes. Also, make sure the toggle button is not too big and distracting, it should be a small icon in the top right.

**Comment by geeks5551** [comment]
Can i work on this issue @sggts04?

**Comment by Priyansh-09** [comment]
I want to work on this @sggts04

**Comment by sggts04** [comment]
@geeks5551 let others get some issues aswell :)

**Comment by basil08** [comment]
can i work on this @sggts04 ?

**Comment by sggts04** [comment]
Hi @basil08 , thanks for your interest. However, this repo is part of an event being held for our organisation. Sorry!

**Comment by basil08** [comment]
i have signed up for hacktoberfest if that is the event you are referring to. i am looking for my first PR to make. if this is not one, can you point to some which are eligible repos? thanks :)

**Comment by Codedude1** [comment]
Is this open? I would like to work.

**Comment by sggts04** [comment]
@Codedude1 you already have two assigned issues in this repo :)

**Comment by Cypherdious89** [comment]
Can I work on this @sggts04 ?

**Comment by kumarmanish03** [comment]
I want to work on it. @sggts04

**Comment by sggts04** [comment]
@kumarmanish03 go ahead
