### ISSUE TITLE
Custom cursor and scrollbar

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#84]
The default cursor and the scrollbar are getting in the way of the overall theme. They need to be customized.
(the cursor doesn't need to be flashy or animated, a simple dot which is visible anywhere in the page would do)

**Comment by sandy9808** [comment]
i can do the scroll bar part only.

**Comment by Priyansh-09** [comment]
Can I do this @tsukii21 ?

**Comment by tsukii21** [comment]
Go ahead. Any contribution is welcome

**Comment by tsukii21** [comment]
@sandy9808 you deal with the scroll bar and @Priyansh-09 finish your currently assigned issues first and then we will see

**Comment by Cypherdious89** [comment]
> 
> 
> @sandy9808 you deal with the scroll bar and @Priyansh-09 finish your currently assigned issues first and then we will see

Can I add the custom cursor part @tsukii21 ??

**Comment by tsukii21** [comment]
@Priyansh-09 No you can not. We will wait to see if a new contributor wants to do it and if no one comes up I will assign it to you. Please do your current tasks for now
